blank_issues_enabled: false
contact_links:
  - name:  질문이나 논의 (Questions or Discussions)
    url: https://github.com/username/ddoddo-market/discussions
    about: 질문이나 논의가 필요하시면 Discussions 탭을 이용해 주세요.
