spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_SET_URI:uri}
          secret-key: ${JWT_SECRET_KEY:secret}
  # 데이터베이스 연결 정보
  datasource:
    url: jdbc:postgresql://localhost:5432/ddoddo_market_db
    username: root
    password: pass1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Cloudflare R2 설정
cloud:
  aws:
    credentials:
      access-key: ${CLOUDFLARE_ACCESS_KEY_ID}
      secret-key: ${CLOUDFLARE_SECRET_ACCESS_KEY}
    s3:
      bucket: ${CLOUDFLARE_R2_BUCKET_NAME} # 예: ddoddo-market-images
      endpoint: https://${CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com # S3 호환 엔드포인트
    region:
      static: auto # R2는 'auto' 리전을 사용합니다.
    stack:
      auto: false

# CORS 전역 설정
cors:
  allowed-origins: "http://localhost:3000" # 프론트엔드의 요청을 허용할 출처
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "Authorization,Content-Type"

# 로깅 설정 추가
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.ddoddo.backend: DEBUG