spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_SET_URI:uri}
          secret-key: ${JWT_SECRET_KEY:secret}
  # 데이터베이스 연결 정보
  datasource:
    url: jdbc:postgresql://localhost:5432/ddoddo_market_db
    username: root
    password: pass1234

# CORS 전역 설정
cors:
  allowed-origins: "http://localhost:3000" # 프론트엔드의 요청을 허용할 출처
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "Authorization,Content-Type"

# 로깅 설정 추가
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.ddoddo.backend: DEBUG